[abbr]
[acronym]
[address]
[applet]
  attributes = [
    { name = "align" },
    { name = "alt" },
    { name = "archive" },
    { name = "code" },
    { name = "codebase" },
    { name = "datafld", override = "DataFld" },
    { name = "datasrc", override = "DataSrc" },
    { name = "height" },
    { name = "hspace", override = "HSpace" },
    { name = "mayscript", override = "MayScript" },
    { name = "name" },
    { name = "object" },
    { name = "src" },
    { name = "vspace", override = "VSpace" },
    { name = "width" }
  ]
[area]
  attributes = [
    { name = "alt" },
    { name = "coords" },
    { name = "download" },
    { name = "href" },
    { name = "hreflang", override = "HrefLang" },
    { name = "media" },
    { name = "referrerpolicy", override = "ReferrerPolicy" },
    { name = "rel" },
    { name = "shape" },
    { name = "target" }
  ]
[article]
[aside]
[audio]
  attributes = [
    { name = "autoplay", override = "AutoPlay" },
    { name = "buffered" },
    { name = "controls" },
    { name = "loop" },
    { name = "mozCurrentSampleOffset", override = "MozCurrentSampleOffset" },
    { name = "muted" },
    { name = "played" },
    { name = "preload" },
    { name = "src" },
    { name = "volume" }
  ]
[b]
[base]
  attributes = [
    { name = "href" },
    { name = "target" }
  ]
[basefont]
  attributes = [
    { name = "color" },
    { name = "face" },
    { name = "size" }
  ]
  override = "BaseFont"
[bdi]
[bdo]
[blockquote]
  attributes = [
    { name = "cite" }
  ]
  override = "BlockQuote"
[body]
  attributes = [
    { name = "onafterprint", override = "OnAfterPrint" },
    { name = "onbeforeprint", override = "OnBeforePrint" },
    { name = "onbeforeunload", override = "OnBeforeUnload" },
    { name = "onblur", override = "OnBlur" },
    { name = "onerror", override = "OnError" },
    { name = "onfocus", override = "OnFocus" },
    { name = "onhashchange", override = "OnHashChange" },
    { name = "onlanguagechange", override = "OnLanguageChange" },
    { name = "onload", override = "OnLoad" },
    { name = "onmessage", override = "OnMessage" },
    { name = "onoffline", override = "OnOffline" },
    { name = "ononline", override = "OnOnline" },
    { name = "onpopstate", override = "OnPopState" },
    { name = "onredo", override = "OnRedo" },
    { name = "onresize", override = "OnResize" },
    { name = "onstorage", override = "OnStorage" },
    { name = "onundo", override = "OnUndo" },
    { name = "onunload", override = "OnUnload" }
  ]
[canvas]
  attributes = [
    { name = "height" },
    { name = "width" }
  ]
[caption]
[cite]
[col]
  attributes = [
    { name = "bgcolor", override = "BGColor" },
    { name = "span" }
  ]
[colgroup]
  attributes = [
    { name = "bgcolor", override = "BGColor" },
    { name = "span" }
  ]
[data]
  attributes = [
    { name = "value" }
  ]
[datalist]
  override = "DataList"
[dd]
[del]
  attributes = [
    { name = "cite" },
    { name = "datetime", override = "DateTime" }
  ]
[details]
  attributes = [
    { name = "open", type = "bool" }
  ]
[dfn]
[dialog]
  attributes = [
    { name = "open", type = "bool" }
  ]
[dl]
[dt]
[em]
[embed]
  attributes = [
    { name = "height" },
    { name = "src" },
    { name = "type" },
    { name = "width" }
  ]
[fieldset]
  attributes = [
    { name = "disabled", type = "bool" },
    { name = "form" },
    { name = "name" }
  ]
  override = "FieldSet"
[figcaption]
  override = "FigCaption"
[figure]
[h2]
[h5]
[h6]
[head]
[header]
[hgroup]
  override = "HGroup"
[html]
  attributes = [
    { name = "xmlns", override = "XMLNS" }
  ]
  override = "HTML"
[ins]
  attributes = [
    { name = "cite" },
    { name = "datetime", override = "DateTime" }
  ]
[kbd]
[legend]
[link]
  attributes = [
    { name = "as" },
    { name = "crossorigin", override = "CrossOrigin" },
    { name = "disabled", type = "bool" },
    { name = "href" },
    { name = "hreflang", override = "HrefLang" },
    { name = "integrity" },
    { name = "media" },
    { name = "methods" },
    { name = "prefetch" },
    { name = "referrerpolicy", override = "ReferrerPolicy" },
    { name = "rel" },
    { name = "sizes" },
    { name = "target" },
    { name = "title" },
    { name = "type" }
  ]
[main]
[map]
  attributes = [
    { name = "name" }
  ]
[mark]
[menu]
  attributes = [
    { name = "type" }
  ]
[meta]
  attributes = [
    { name = "charset", override = "CharSet" },
    { name = "content" },
    { name = "http-equiv", override = "HTTPEquiv" },
    { name = "name" }
  ]
[meter]
  attributes = [
    { name = "value", type = "float64" },
    { name = "min", type = "float64" },
    { name = "max", type = "float64" },
    { name = "low", type = "float64" },
    { name = "high", type = "float64" },
    { name = "optimum", type = "float64" },
    { name = "form" }
  ]
[noscript]
  override = "NoScript"
[object]
  attributes = [
    { name = "data" },
    { name = "form" },
    { name = "height" },
    { name = "name" },
    { name = "type" },
    { name = "typemustmatch", override = "TypeMustMatch" },
    { name = "usemap", override = "UseMap" },
    { name = "width" }
  ]
[ol]
  attributes = [
    { name = "compact" },
    { name = "reversed", type = "bool" },
    { name = "start" },
    { name = "type" }
  ]
[optgroup]
  attributes = [
    { name = "disabled", type = "bool" },
    { name = "label" }
  ]
  override = "OptGroup"
[output]
  attributes = [
    { name = "for" },
    { name = "form" },
    { name = "name" }
  ]
[param]
  attributes = [
    { name = "name" },
    { name = "value" }
  ]
[picture]
[progress]
  attributes = [
    { name = "max", type = "float64" },
    { name = "value", type = "float64" }
  ]
[q]
  attributes = [
    { name = "cite" }
  ]
[rp]
  override = "RP"
[rt]
  override = "RT"
[rtc]
  override = "RTC"
[ruby]
# [s]
[samp]
[script]
  attributes = [
    { name = "async" },
    { name = "crossorigin", override = "CrossOrigin" },
    { name = "defer" },
    { name = "integrity" },
    { name = "nomodule", override = "NoModule" },
    { name = "nonce" },
    { name = "src" },
    { name = "text" },
    { name = "type" },
  ]
[section]
[slot]
  attributes = [
    { name = "name" }
  ]
[small]
[source]
  attributes = [
    { name = "sizes" },
    { name = "src" },
    { name = "srcset", override = "SrcSet" },
    { name = "type" },
    { name = "media" }
  ]
[strong]
[style]
  attributes = [
    { name = "type" },
    { name = "media" },
    { name = "nonce" },
    { name = "title" }
  ]
[sub]
[tbody]
  attributes = [
    { name = "bgcolor", override = "BGColor" }
  ]
[td]
  attributes = [
    { name = "bgcolor", override = "BGColor" },
    { name = "colspan", override = "ColSpan" },
    { name = "headers" },
    { name = "rowspan", override = "RowSpan" }
  ]
[template]
[tfoot]
  attributes = [
    { name = "bgcolor", override = "BGColor" }
  ]
[th]
  attributes = [
    { name = "abbr" },
    { name = "bgcolor", override = "BGColor" },
    { name = "colspan", override = "ColSpan" },
    { name = "headers" },
    { name = "rowspan", override = "RowSpan" },
    { name = "scope" }
  ]
[thead]
  attributes = [
    { name = "bgcolor", override = "BGColor" }
  ]
[time]
  attributes = [
    { name = "datetime", override = "DateTime" }
  ]
[title]
[tr]
[track]
  attributes = [
    { name = "default", type = "bool" },
    { name = "kind" },
    { name = "label" },
    { name = "src" },
    { name = "srclang", override = "SrcLang" }
  ]
[u]
# [var]
# [video]
#   attributes = [
#     { name = "autoplay" },
#     { name = "buffered" },
#     { name = "controls" },
#     { name = "crossorigin", override = "CrossOrigin" },
#     { name = "height" },
#     { name = "loop" },
#     { name = "muted" },
#     { name = "played" },
#     { name = "preload" },
#     { name = "poster" },
#     { name = "src" },
#     { name = "width" },
#     { name = "playsinline", override = "PlaysInline" }
#   ]
[wbr]
